name: Node.js App Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run Node.js app
        run: node app.js

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: welcome-app-service
          slot-name: production # Optional: Specify if deploying to a specific slot
          publish-profile: ${{ secrets.AZURE_APP_PUBLISH_PROFILE }}
          package: .

      - name: Clean up
        run: npm run clean # Optional: Add cleanup steps if needed
